name: Deploy Mail Service to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodlari Cek
      uses: actions/checkout@v4

    - name: Anahtarlari Ayarla
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Sunucuya Baglan ve Guncelle
      run: |
        ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          set -e

          # Klasör yoksa indir, varsa içine gir
          if [ ! -d "iskapisi-mail-servisi" ]; then
            git clone https://github.com/${{ github.repository }}.git iskapisi-mail-servisi
          fi

          cd iskapisi-mail-servisi
          git pull origin main

          echo "MAIL_HOST=smtp.gmail.com" > .env
          echo "MAIL_PORT=587" >> .env
          echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> .env
          echo "MAIL_PASS=${{ secrets.MAIL_PASS }}" >> .env



          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          pkill -f uvicorn || true
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > mail.log 2>&1 &
        EOF
